\input texinfo       @c                    -*- Texinfo -*-
@c %**start of header
@setfilename libdimensionxx.info
@settitle The Dimension 3-D Rendering Library, C++ Interface
@c %**end of header

@copying
Copyright @copyright{} 2009 Tavian Barnes
@end copying

@titlepage
@title The Dimension C++ Library
@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@contents

@ifnottex
@node Top
@top The Dimension C++ Library

@insertcopying
@end ifnottex

@menu
* Type Index::
* Function Index::
* Concept Index::
@end menu


@node Type Index
@unnumbered Type Index

@printindex tp


@node Function Index
@unnumbered Function Index

@printindex fn


@node Concept Index
@unnumbered Concept Index

@printindex cp

@bye
